services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-appdb}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD:-root}"]
      interval: 5s
      timeout: 5s
      retries: 30

  migrate:
    image: migrate/migrate:v4.17.1
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api/migrations:/migrations:ro
    entrypoint: ["/bin/sh", "-lc"]
    command: >
      "
      for i in 1 2 3 4 5; do
        migrate -path=/migrations -database 'mysql://app:app@tcp(mysql:3306)/appdb?multiStatements=true' up && exit 0;
        echo 'migration failed, retrying...';
        sleep 3;
      done;
      exit 1
      "
  #      "migrate
  #      -path=/migrations
  #      -database 'mysql://app:app@tcp(mysql:3306)/appdb?multiStatements=true'
  #      up"
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 30

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MGMT_PORT:-15672}:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 30

  api:
    build:
      context: ./api
    restart: on-failure
    environment:
      APP_ENV: ${APP_ENV:-dev}
      PORT: ${API_PORT:-8080}

      MYSQL_DSN: ${MYSQL_DSN:-app:app@tcp(mysql:3306)/appdb?parseTime=true&charset=utf8mb4&loc=Local}
      REDIS_ADDR: ${REDIS_ADDR:-redis:6379}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@rabbitmq:5672/}

      JWT_SECRET: ${JWT_SECRET:-dev_secret_change_me}
    ports:
      - "${API_PORT:-8080}:8080"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

volumes:
  mysql_data:
